version: "3"
services:
  app:
    image: github.com/ad/go-githublistener:latest
    ports:
      - 8080:8080
    volumes:
      - ./db:/db
    environment:
      - GO_GITHUB_LISTENER_PORT=${GO_GITHUB_LISTENER_PORT}
      - GO_GITHUB_LISTENER_HTTP_REDIRECT_URI=${GO_GITHUB_LISTENER_HTTP_REDIRECT_URI}
      
      - GO_GITHUB_LISTENER_CLIENT_ID=${GO_GITHUB_LISTENER_CLIENT_ID}
      - GO_GITHUB_LISTENER_CLIENT_SECRET=${GO_GITHUB_LISTENER_CLIENT_SECRET}

      - GO_GITHUB_LISTENER_TELEGRAM_TOKEN=${GO_GITHUB_LISTENER_TELEGRAM_TOKEN}
      - GO_GITHUB_LISTENER_TELEGRAM_PROXY_HOST=${GO_GITHUB_LISTENER_TELEGRAM_PROXY_HOST}
      - GO_GITHUB_LISTENER_TELEGRAM_PROXY_PORT=${GO_GITHUB_LISTENER_TELEGRAM_PROXY_PORT}
      - GO_GITHUB_LISTENER_TELEGRAM_PROXY_USER=${GO_GITHUB_LISTENER_TELEGRAM_PROXY_USER}
      - GO_GITHUB_LISTENER_TELEGRAM_PROXY_PASSWORD=${GO_GITHUB_LISTENER_TELEGRAM_PROXY_PASSWORD}
      - GO_GITHUB_LISTENER_TELEGRAM_DEBUG=${GO_GITHUB_LISTENER_TELEGRAM_DEBUG}
